### ISSUE TITLE
compatibility with ttypescript

### ISSUE THREAD

**Issue by amir-arad** [AviVahl/ts-tools#10]
is it possible to use [ttypescript](https://github.com/cevek/ttypescript) transformers?

**Comment by AviVahl** [comment]
I personally don't like the approach of `ttypescript`. They patch `createProgram`: https://github.com/cevek/ttypescript/blob/master/packages/ttypescript/src/patchCreateProgram.ts#L33

That being said, if `createProgram` is patched before `@ts-tools/service` initializes its `LanguageService`, then their approach will _probably_ work. I use official typescript APIs to load config and init everything.

As for general custom transformers support, `@ts-tools/service` already supports it (via programmatic API):
https://github.com/AviVahl/ts-tools/blob/%40ts-tools/service%402.0.0/packages/service/src/types.ts#L50

`@ts-tools/webpack-loader` and `@ts-tools/node` don't currently allow specifying custom transformers. 
Getting the `webpack-loader` to support it via webpack configuration would be easy. The `node` package is another story. I don't want to have users modify their `tsconfig.json` with unofficial options. I could search for a predefined transformer-factory-exporting file name, but that feels like a stretch in trying to achieve functionality that should probably come from TypeScript itself.

**Comment by amir-arad** [comment]
thanks
