### ISSUE TITLE
[build] - Watch mode

### ISSUE THREAD

**Issue by rkovalyov** [AviVahl/ts-tools#159]
Do you plan to support watch mode ?

**Comment by AviVahl** [comment]
I could, but I actually thought about deprecating it now that project references are usable. WDYT? :)

**Comment by rkovalyov** [comment]
@AviVah thanks for quickly reply, l I've not dived into `project references` yet, just read [Project References Doc](https://www.typescriptlang.org/docs/handbook/project-references.html). 
I already created own build scripts (webpack, gulp, storybook) based on yours great tools ). I know that running ts programatically from node fully annoying and hard to manage.

**Comment by rkovalyov** [comment]
Another point, would be nice to move code from line 32 to `build` scripts
https://github.com/AviVahl/ts-tools/blob/main/packages/build/src/cli.ts#L32

it would give possible to run it `programatically` from own special tools

I want to control all scripts from one place for all project

**Comment by AviVahl** [comment]
"build" package has now been removed from repository. last published one still available from `npm`.
