### ISSUE TITLE
[build] - public API for build process

### ISSUE THREAD

**Issue by rkovalyov** [AviVahl/ts-tools#163]
Could u please open API for build, it really helps me to wrap process inside my own build scripts ? WDYT ?:)

move code from ``cli.ts` line 32 to build.ts scripts
https://github.com/AviVahl/ts-tools/blob/main/packages/build/src/cli.ts#L32

**Comment by AviVahl** [comment]
As I mentioned in #159, I'm planning to deprecate the `@ts-tools/build` package. I'm finishing up migrating several repositories still using it to project references, and then it will be retired.
However, feel free to take any piece of useful code from it. It's MIT exactly for this reason. :)

**Comment by rkovalyov** [comment]
ok, thanks )

**Comment by rkovalyov** [comment]
@rkovalyov Just to get knowledge, finally Do you expect to run build by `tsc --build` in project what you migrating to project references?

**Comment by AviVahl** [comment]
Yeah, and you can actually see several setups using it here:
https://github.com/wixplosives/sample-monorepo
https://github.com/wixplosives/file-services

**Comment by rkovalyov** [comment]
@AviVahl How to deal with developing own build scripts (bin) for closing api from other developers, and control it from one repo ?

**Comment by AviVahl** [comment]
Not sure I understand what you're asking... Could you clarify what it is you are trying to achieve?
What do you mean by "how to deal", "closing api", and "control it"?

If you need to create a cli, you reference an entry point (with a shebang comment at the top) from the `package.json` with the "bin" field.
For any npm package, you can also expose whatever you choose as a public API (through the "exports" or "main" fields).
If you're using newer Node versions, you can control which files (internal to your package) can be imported from outside using the "exports" field.
Several npm packages can co-exist in a mono-repo (such as `ts-tools`), referencing one another, allowing you to control the used APIs and develop packages in parallel. Each of those packages can define bin entries.

**Comment by rkovalyov** [comment]
@AviVahl  I mean run programatically `tsc --build` and for example handling css by `gulp`, 

so finally, instead of concurrently running  `concurrently "tsc --build" "build css" `, wrap all logic in own cli tool and run `my-own-scripts build`
