### ISSUE TITLE
Type import warning

### ISSUE THREAD

**Issue by idoros** [AviVahl/ts-tools#18]
With the new `1.0.0` version, `Webpack` warns on missing export for a re-export of a type definition with no runtime alias. For example:

```ts
/*internal.ts*/
export type SomeType = any;
/*re-export.ts*/
export { SomeType } from './internal';
/*main.ts*/
import {SomeType} from './re-export';
/*
WARNING in ./index.ts                                                                                                                                              
 export 'SomeType' was not found in './internal'
 @ ./main.ts
 @ multi ./main.ts
*/
```

I think this happens because type exports are erased from the origin file on transform, but kept as dependencies at the end module that used the definition. but I'm not sure when are they being erased in the normal flow.

Maybe a solution could be to have the `on-the-fly transpilation` replace type exports with runtime symbols for dev?

 ## Workaround

Changing the re-export can prevent this:

```ts
/*re-export.ts*/
export * from './internal';

// OR

import { SomeType } from './internal';
export type SomeType = SomeType
```

> I thought about putting a filter in the Webpack configuration, but that would also hide real import misses.

**Comment by AviVahl** [comment]
v1 of `@ts-tools/node` and `@ts-tools/webpack-loader` creating full-pledged type-checking `ts.Program` instances, and instead do "simple" (and much faster!) transformation using `ts.transpileModule`.

This has several trade-offs, but acceptable ones if you ask me.

Re-exports of types/interfaces are not removed, as there's no type checking. TypeScript cannot tell if an imported symbol is a type or runtime value, and leave it there.

This doesn't really affect `@ts-tools/node`, as it always transpiles to `module: "commonjs"` (where the symbol gets undefined and there's no validation).

`@ts-tools/webpack-loader`, on the other hand, is affected. It forces `module: "esnext"`, which allows webpack to optimize and validate esm-to-esm imports/exports. webpack then tries finding SomeType and warns about a missing symbol.

The workarounds you've suggested are good ones. I mostly use `export * from`. If I want to re-export a specific symbol, I use:
`export type SomeType = import('./internal').SomeType`
the above statement is easily identifiable by the compiler as a type-only import, and is being properly removed during transpilation.

Another transformation which behaves differently is not inlining `const enum` values.

I'm closing this as a "design limitation" of the currently chosen approach. Should probably document some of this in the README...

**Comment by AviVahl** [comment]
https://github.com/microsoft/TypeScript/issues/34750

**Comment by idoros** [comment]
> export type SomeType = import('./internal').SomeType

Notice that you need to pass generics when reexporting like this:
```ts
export type SomeType<T> = import('./internal').SomeType<T>
```

**Comment by AviVahl** [comment]
Yeah actually found that out a while ago. Annoying, so `export * from` it is.
