### ISSUE TITLE
[webpack-loader] - Possibility to apply React Refresh Webpack Plugin 

### ISSUE THREAD

**Issue by rkovalyov** [AviVahl/ts-tools#191]
Hi, hope u are doing well :)

Could we make API for applying [`react-refresh-plugin`](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/README.md)   like did `ts-loader`
```
{
    loader: require.resolve('ts-loader'),
      options: {
         getCustomTransformers: () => ({
            before: isDevelopment ? [ReactRefreshTypeScript()] : [],
          }),
      }, 
},
```

**Comment by AviVahl** [comment]
Oh, I apologize. I think the README is outdated.
It already accepts a transformers field:
https://github.com/AviVahl/ts-tools/blob/%40ts-tools/webpack-loader%402.1.1/packages/webpack-loader/src/typescript-loader.ts#L79

There's no cache invalidation logic for the transformer yet, so you may need to `rm -rf node_modules/.cache` once if you previously transpiled without the transformer locally.

**Comment by AviVahl** [comment]
Oh, using transformers turns off the caching mechanism.

If you want it to cache during dev time (when applying the transformer), you may turn on caching explicitly (using the `"cache"` option), but may also need to point each mode (production/development) to a different cache directory (using the `"cacheDirectoryPath"` option).

**Comment by AviVahl** [comment]
In future versions, I might allow a "cacheToken" option (provided via loader options) that allows automatically separating cache directories.

**Comment by rkovalyov** [comment]
@AviVahl  thanks for explanation 👍

**Comment by AviVahl** [comment]
Happy to help. Feel free to re-open if issue is not resolved.
