### ISSUE TITLE
[service] TypeScriptService constructor arguments

### ISSUE THREAD

**Issue by cspotcode** [AviVahl/ts-tools#7]
The JSDoc for TypeScript service says I can pass options to the constructor, but it doesn't have one.
https://github.com/AviVahl/ts-tools/blob/master/packages/service/src/service.ts#L60

Is this something coming in a future version, or did you decide to go for a different API?

**Comment by AviVahl** [comment]
The API changed and I forgot to update the docs. Will do, thanks.
The options moved to second parameter of `transpileFile()`.

**Comment by AviVahl** [comment]
fixed in `@ts-tools/service@1.0.4`
