### ISSUE TITLE
[build] - `AllowJs`  option doesnt work

### ISSUE THREAD

**Issue by rkovalyov** [AviVahl/ts-tools#70]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-the-error-ts5055-cannot-write-file-xxxjs-because-it-would-overwrite-input-file-when-using-javascript-files

as Result we got issue
`error TS5055: Cannot write file '**/*.js' because it would overwrite input file.`

Need to set `outDir` depends on arguments (--cjs or --esm)

**Comment by AviVahl** [comment]
Thanks for the report.

Could you check if `@ts-tools/build@2.1.1` fixes the issue on your end? Feel free to re-open if not.

Just a small note, `ts-build` will not automatically add "outDir" to be passed to typescript (even though it creates two of them). It now proxies the one you set in `tsconfig.json`, but uses its own logic to determine where the output should be saved.

**Comment by rkovalyov** [comment]
@AviVahl thanks,
just to be aware  it doest not proxy `outDir` from `tsconfig.json`,
but it works as expected with `--out-dir` argument
