### ISSUE TITLE
[service] skip the typechecker but *do* perform tsconfig lookup?

### ISSUE THREAD

**Issue by cspotcode** [AviVahl/ts-tools#8]
It looks like the `isolated` flag skips type-checking and *also* skips tsconfig lookup.

Is there a way to perform tsconfig lookup (for flags like `downlevelIteration` and `target` that affect emitted code) but still skip type-checking?

**Comment by AviVahl** [comment]
I wanted this for `@ts-tools/node` as well. Will probably add support for it soon.
Appreciate the feedback!

**Comment by cspotcode** [comment]
Thanks!  And thanks for the quick fix on those other 2 issues.

This module is saving me a ton of time.  Often I wish tsc did something slightly different (logging diagnostics as JSON, skipping the typechecker, etc)  It's historically been too annoying to re-implement the basic tsc infrastructure to get to a point where I can implement my behavior on top.  `@ts-tools/service` makes it super-easy.

**Comment by cspotcode** [comment]
Here's the workaround I'm using for this, similar to the workaround in #9.

```
A related use-case: transpiling a file *without* type-checking, but *with* the compiler options from tsconfig.  Do the same trick above to load the tsconfig, then do:

```
import { TypeScriptService } from '@ts-tools/service';
const service = new TypeScriptService();
// Trigger discovery and parsing of tsconfig
service.transpileFile('DOES NOT EXIST.ts', {
  tsconfigFileName : 'tsconfig.json',
  getCompilerOptions = (baseHost, tsconfigOptions) =>tsconfigOptions
});
const runningService = service.runningServices.get('tsconfig.json')!;
// Get parsed compiler options
const parsedCompilerOptions = runningService.languageService.getProgram()!.getCompilerOptions();
// transpile file *without* typechecking *with* our tsconfig's compiler options
service.transpileFile('foo.ts', {
  isolated: true,
  getCompilerOptions = (baseHost, tsconfigOptions) =>parsedCompilerOptions
});
```

**Comment by AviVahl** [comment]
Happy to hear this package helps others. :+1: 

I already have some WIP to resolve this issue, but it might have to wait for the weekend, when I have more free time.

**Comment by AviVahl** [comment]
apologies for the delay. going to release service@2.0.0 that allows this.
